### ISSUE TITLE
PokemonIDTable: Regions are unnecessary

### ISSUE THREAD

**Issue by Goliatack007** [Mitsukiii/PokeTwo#5]
The PokeIDs are the same regardless where u find them. Sometimes the bot doesnt get the right RegionTable. Isnt it easier to have a list with the PokeIDs only ? So you dont have to add the Pokemons again if the bot fails to read the right region.

so instead of:

```
[1128792064]
Name=Mt. Silver Expert Belt
1=None
55=Graveler
31=Onix
32=Teddiursa
41=Phanpy
53=Donphan
63=Ursaring
42=Golbat
60=Golduck
43=Goldeen
16=Pupitar
38=Parasect
39=Quagsire
[1134198784]
Name=Mt. Silver Expert Belt
1=None
55=Graveler
31=Onix
32=Teddiursa
41=Phanpy
53=Donphan
63=Ursaring
42=Golbat
60=Golduck
43=Goldeen
16=Pupitar
39=Quagsire
38=Parasect
```
use this:
```
1=None
55=Graveler
31=Onix
32=Teddiursa
41=Phanpy
53=Donphan
63=Ursaring
42=Golbat
60=Golduck
43=Goldeen
16=Pupitar
38=Parasect
39=Quagsire
38=Arbok
32=Tangela
87=Ponyta
69=Dodrio
26=Poliwag
36=Magikarp
....
```

**Comment by Mitsukiii** [comment]
I added the Maps cuz some Pokemon have the same ID

Goliatack007 <notifications@github.com> schrieb am So., 26. Aug. 2018,
15:52:
